Cineaste.Web/Controllers/MainPageController.cs
using Cineaste.Data.Models;
using Cineaste.Service.moviesService;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace Cineaste.Web.Controllers
{
    [RequireHttps]
    public class MainPageController : Controller
    {
        IMovieService movieService=null;

        public MainPageController()
        {
            movieService=new MovieService();
        }
        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        movieService.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
        //
        // GET: /MainPage/
        public ActionResult Index()
        {
            

            var allMovies = movieService.GetMovies();
            return View(allMovies.ToList());
        }

        public ActionResult MoviesIndex()
        {
            return View();
        }

        //
        // GET: /MainPage/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /MainPage/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /MainPage/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /MainPage/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /MainPage/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /MainPage/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /MainPage/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Cineaste.Web/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Cineaste.Data.Models;

namespace Cineaste.Web.Controllers
{
    public class MovieController : Controller
    {
        private cineastdbContext db = new cineastdbContext();

        // GET: /Movie/
        public ActionResult Index()
        {
            var movies = db.movies.Include(m => m.boxoffice).Include(m => m.user);
            return View(movies.ToList());
        }

        // GET: /Movie/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            movie movie = db.movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        // GET: /Movie/Create
        public ActionResult Create()
        {
            ViewBag.boxoffice_id = new SelectList(db.boxoffices, "id", "type");
            ViewBag.owner_id = new SelectList(db.users, "id", "address");
            return View();
        }

        // POST: /Movie/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="id,budget,dateOfRealise,genre,nb,sommeNb,photo,signalisation,synopsis,theme,title,trailer,boxoffice_id,owner_id")] movie movie)
        {
            if (ModelState.IsValid)
            {
                db.movies.Add(movie);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.boxoffice_id = new SelectList(db.boxoffices, "id", "type", movie.boxoffice_id);
            ViewBag.owner_id = new SelectList(db.users, "id", "address", movie.owner_id);
            return View(movie);
        }

        // GET: /Movie/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            movie movie = db.movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            ViewBag.boxoffice_id = new SelectList(db.boxoffices, "id", "type", movie.boxoffice_id);
            ViewBag.owner_id = new SelectList(db.users, "id", "address", movie.owner_id);
            return View(movie);
        }

        // POST: /Movie/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="id,budget,dateOfRealise,genre,nb,SommeNb,photo,signalisation,synopsis,theme,title,trailer,boxoffice_id,owner_id")] movie movie)
        {
            if (ModelState.IsValid)
            {
                db.Entry(movie).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.boxoffice_id = new SelectList(db.boxoffices, "id", "type", movie.boxoffice_id);
            ViewBag.owner_id = new SelectList(db.users, "id", "address", movie.owner_id);
            return View(movie);
        }

        // GET: /Movie/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            movie movie = db.movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        // POST: /Movie/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            movie movie = db.movies.Find(id);
            db.movies.Remove(movie);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Cineaste.Web/Controllers/MoviesController.cs
using Cineaste.Data.Models;
using Cineaste.Service.moviesService;
using Cineaste.Service.moviesServices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using System.IO;
using Cineaste.Domain;

namespace Cineaste.Web.Controllers
{
    public class MoviesController : Controller
    {

        IMovieService movieService = null;
       
        public MoviesController()
        {
            movieService = new MovieService();
        }
        //
        // GET: /Movies/
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            int pageSize = 3;
            int pageNumber = (page ?? 1);
            var allMovies = movieService.GetMovies();

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;


            if (!String.IsNullOrEmpty(searchString))
            {
                allMovies = allMovies.Where(s => s.title.Contains(searchString)
                                       || s.genre.Contains(searchString));
            }


            return View(allMovies.ToPagedList(pageNumber, pageSize));
        }

        //
        // GET: /Movies/Details/5
        public ActionResult Details(int id)
        {

            var movie = movieService.GetMovie(id);
            return View(movie);
        }

        //
        // GET: /Movies/Create

        public ActionResult Create()
        {

            return View();
        }

     
        //upload*********************************************
        [HttpPost]
        [ValidateAntiForgeryToken]
        public void  Upload(HttpPostedFileBase photo)
        {
            string directory = @"E:\esprit\4GL1\PI-Dev\server\PiDevServer\jboss-as-7.1.1.Final\welcome-content\image\";

            if (photo != null && photo.ContentLength > 0)
            {
                string fileName = Path.GetFileName(photo.FileName);
                transaction.getInstanceOf().ImageName = fileName;
                photo.SaveAs(Path.Combine(directory, fileName));
            }

            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public void Uploadvideo(HttpPostedFileBase video)
        {
            string directory2 = @"E:\esprit\4GL1\PI-Dev\server\PiDevServer\jboss-as-7.1.1.Final\welcome-content\Video\";

            if (video != null && video.ContentLength > 0)
            {
                string fileName2 = Path.GetFileName(video.FileName);
                transaction.getInstanceOf().VideoName = fileName2;
                video.SaveAs(Path.Combine(directory2, fileName2));
            }

            
        }

       
        //********************************
        //
        // POST: /Movies/Create
        [HttpPost]
      
        public ActionResult Create(movie newMovie)
        {

            // TODO: Add insert logic here
            //formulaire
            
            if (ModelState.IsValid)
            {
                newMovie.ImgUrl = "image/" + transaction.getInstanceOf().ImageName;
                newMovie.trailer = transaction.getInstanceOf().VideoName.Remove(transaction.getInstanceOf().VideoName.Length-4);

            movieService.CreateMovie(newMovie);
            movieService.Commit();
            return RedirectToAction("Index");

            }
            return View();

        }

        //
        // GET: /Movies/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Movies/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Movies/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Movies/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Cineaste.Web/Views/Movie/MainPage/Index.cshtml
@model IEnumerable<Cineaste.Data.Models.movie>
@*@model PagedList.IPagedList<Cineaste.Data.Models.movie>
@using PagedList.Mvc;*@

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Template/CineastTemplate.cshtml";
}
@* caroussel *@
<div id="content" style="width:inherit">
    <div class="carousel-wrapper">
        <div class="carousel">

            <div class="content">
                <h2 class="page-header">MOVIES</h2>

                <a class="carousel-prev" href="detail.html">Previous</a>
                <a class="carousel-next" href="detail.html">Next</a>
                <ul>
@foreach (var item in Model) {
                    <li>
                        <div class="image">
                            @Html.ActionLink(".", "Details/"+item.id, "Movies")
                            <img src="@string.Concat("http://localhost:2000/",  item.ImgUrl)"  alt="@string.Concat("http://localhost:2000/",  item.ImgUrl)" style="height:200px;width:225px " />
                        </div>

                        <!-- /.image -->
                        <div class="title">
                            @*@Html.DisplayFor(modelItem => item.title)*@
                            
                            <h3>@Html.ActionLink(item.title + "", "Details/" + item.id, "Movies")</h3>
                        </div>
                        <!-- /.title -->
                        <div class="location">@Html.DisplayFor(modelItem => item.genre)</div>
                        <!-- /.location-->
                        <div class="price">@Html.DisplayFor(modelItem => item.budget)</div>
                        <!-- .price -->
                        <div class="area">
                            <span class="key">date</span>
                            <span class="value">@Html.DisplayFor(modelItem => item.dateOfRealise)</span>
                        </div>
                        <!-- /.area -->
                        <div class="bathrooms">
                            @*<div class="inner">@Html.DisplayFor(modelItem => item.sommeNb )</div>*@
                        </div>
                        <!-- /.bathrooms -->


                    </li>
}
                </ul>
            </div>
            <!-- /.content -->
        </div>
        <!-- /.carousel -->
    </div>
    <!-- /.carousel-wrapper -->
</div>

@* carousselEND *@

@* grid and filter *@
<div class="container" >

    <div id="main">
        <div class="row" >
            <div class="span12">

                <!-- /.properties-rows -->
                <div class="properties-grid">
                    <div class="row">

                        @foreach (var item in Model)
                        {
                            <div class="property span3">
                                <div class="image">
                                    <div class="content">
                                        @Html.ActionLink(".", "Details/" + item.id, "Movies")
                                        <img src="@string.Concat("http://localhost:2000/",  item.ImgUrl)" alt="" style="height:200px;width:275px ">
                                    </div>
                                    <!-- /.content -->
                                    <!-- /.reduced -->
                                </div>
                                <!-- /.image -->

                                <div class="title">
                                    <h2>@Html.ActionLink(item.title + "", "Details/" + item.id, "Movies")</h2>
                                </div>
                                <!-- /.title -->

                                <div class="location">@Html.DisplayFor(modelItem => item.genre)</div>
                                <!-- /.location -->
                                <div class="area">
                                    <span class="key">Date:</span><!-- /.key -->
                                    <span class="value">@Html.DisplayFor(modelItem => item.dateOfRealise)</span><!-- /.value -->
                                </div>

                                <!-- /.bedrooms -->
                                <div class="bathrooms">
                                    @*<div class="content">@Html.DisplayFor(modelItem => item.sommeNb)</div>*@
                                </div>
                                <!-- /.bathrooms -->
                            </div>
                        }
                        <!-- /.property -->
                        <!-- /.property -->
                    </div>
                    <!-- /.row -->
                </div>
                <!-- /.properties-grid -->
                @*<div class="pagination pagination-centered">
                        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
                        <ul>
                            <li>
                                @Html.PagedListPager(Model, page => Url.Action("Index",
                                     new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
                        </li>

                    </ul>
                </div>*@
                <!-- /.pagination -->
                <!-- /.pagination -->
            </div>


        </div>
    </div>
</div>

@* grid and filter end *@

 